# Generated by Django 4.0.2 on 2022-03-07 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='dog',
            options={'ordering': ('name',)},
        ),
    ]
