# Generated by Django 4.0.2 on 2022-03-07 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_breed_dog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerscore',
            name='game',
        ),
        migrations.RemoveField(
            model_name='playerscore',
            name='player',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='GameCategory',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='PlayerScore',
        ),
    ]
